### ISSUE TITLE
If cache is not hist in restore, there is not cache-hit output

### ISSUE THREAD

**Issue by AGallouin** [MartijnHols/actions-cache#1]
Hi !

Looking at the code, it seems that the branch managing the cache not hit in restore.ts doesn't set output before returning:

```
         if (!cacheKey) {
            const message = `Cache not found for input keys: ${[
                primaryKey,
                ...restoreKeys
            ].join(", ")}`;
            if (isCacheRequired()) {
                throw new Error(message);
            } else {
                core.info(message);
                // I expected to have an utils.setCacheHitOutput(false); here
                return false;
            }
        }
```

I may be missing something here, If right I can write you the PR.

Thanks !

**Comment by MartijnHols** [comment]
Hey, thanks for reporting your findings. Looking at the code, I see this originates from the original repo here: https://github.com/actions/cache/blob/8f1e2e02865c42348f9baddbbaafb1841dce610a/src/restore.ts#L33-L46

This probably works properly since most people use `steps.cache.outputs.cache-hit != 'true'` as a check rather than checking for false, and the default should be blank (falsey). Still for clarity I agree it would be better for that line to be in there. Are you still willing to make a PR for the change?
