### ISSUE TITLE
With 3.0.3  cache stopped working

### ISSUE THREAD

**Issue by yatinappsmith** [MartijnHols/actions-cache#2]
![image](https://user-images.githubusercontent.com/84702014/165652783-6b103676-4058-4629-b654-cf43f28be0e9.png)

**Comment by MartijnHols** [comment]
Sorry about that. This was fixed in 3.0.4. Tests would have caught this, so to prevent an issue like this from happening again I also enabled branch protection so future commits go through a PR flow that enforces the status checks. This will slow down my development slightly, but I'd rather not break this.

At a later time I'd also like to improve reliability by setting up an end-to-end test through an actions workflow rather than just testing using unit tests. This should catch this as well. Finally adding something like semantic release would also make fixes and releases easier, as well as provide proper changelogs automatically.
